---
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- value: Executam os mesmos comandos, na mesma ordem e chegam ao mesmo tabuleiro final.
  checked: false
- value: Executam os mesmos comandos, em ordem diferente e chegam ao mesmo tabuleiro
    final.
  checked: false
- value: Executam os mesmos comandos, em ordem diferente e chegam a diferentes tabuleiros
    no final.
  checked: true
- value: Executam os mesmos comandos, na mesma ordem e chegam a diferentes tabuleiros
    no final.
  checked: false
name: A ordem dos fatores altera o produto
